# Generated by Django 3.2.15 on 2022-12-22 11:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Цветовой HEX-код (например, #49B64E)', image_field=None, max_length=7, samples=None, verbose_name='Цвет тега'),
        ),
    ]
