# Generated by Django 3.2.15 on 2022-12-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221208_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_recipes',
            field=models.ManyToManyField(related_name='users', to='recipes.Recipe'),
        ),
    ]
