# Generated by Django 3.2.15 on 2022-12-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20221213_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Картинка, закодированная в Base64', upload_to='', verbose_name='Изображение рецепта'),
        ),
    ]
