# Generated by Django 3.2.15 on 2022-12-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Картинка, закодированная в Base64', upload_to='recipes/', verbose_name='Изображение рецепта'),
        ),
    ]
